name: Update Readme

on:
  # schedule:
  # - cron: '0 0 * * *' # Runs every day at midnight UTC
  # push:
  #   branches:
  #   - main # Change this to your main branch name
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run script
      run: uv run python src/main.py
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m 'CI: readme updated'
          git push
        else
          echo "No changes to commit"
        fi
